#!/usr/bin/env node
// ============================================================================
// Verify a database has every critical object the application depends on.
//
//   node scripts/db/verify-schema.js
//
// Exits 0 when all tables and functions exist, 1 listing the missing ones.
// Used by CI after applying supabase/ci/stub_auth.sql + all migrations, and by
// hand after applying migrations to the live Supabase database.
// In addition to the canonical object lists below, the FRONTEND CONTRACT
// (supabase/api-contract.json, generated by scripts/db/gen-contract.js from
// src/api/domains + src) is compared against the database: every RPC and table
// the frontend calls must exist, so a database behind the frontend fails here
// before it can ever reach the parity gate / a published page.
// Configuration is read ONLY from .env: SUPABASE_DB_URL / DATABASE_URL / POSTGRES_URL.
// ============================================================================

import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const __dirname = resolve(fileURLToPath(import.meta.url), '..');
const ROOT = resolve(__dirname, '..', '..');

const EXPECTED_TABLES = [
  'branches', 'warehouses', 'categories', 'products', 'product_units', 'inventory',
  'customers', 'suppliers', 'sales', 'sale_items', 'purchases', 'purchase_items',
  'expenses', 'users', 'audit_log', 'settings', 'branch_settings', 'units', 'stock_transactions',
  'product_components', 'shifts', 'shift_operations', 'roles', 'document_sequences',
  'raw_materials', 'raw_material_inventory', 'raw_material_batches', 'recipes',
  'recipe_items', 'production_orders', 'production_waste', 'inventory_batches',
  'inventory_ledger', 'warehouse_transfers', 'warehouse_transfer_items',
  'chart_of_accounts', 'journal_entries', 'journal_entry_lines', 'account_mappings',
  'customer_payments', 'supplier_payments', 'treasury_accounts', 'treasury_transactions',
  'bank_reconciliations', 'bank_statement_lines', 'dining_areas', 'dining_tables',
  'orders', 'order_items', 'order_kitchen_sends', 'schema_migrations', 'login_as_log',
  'purchase_requests', 'purchase_request_items', 'rfqs', 'rfq_items',
  'supplier_quotations', 'supplier_quotation_items', 'purchase_receipts', 'purchase_receipt_items',
];

const EXPECTED_FUNCTIONS = [
  'is_pos_admin', 'get_branch_id', 'get_user_role', 'set_updated_at',
  'next_document_number', 'create_user', 'seed_opening_balances',
  'process_sale', 'process_purchase', 'process_refund', 'process_expense',
  'adjust_stock', 'receive_payment', 'pay_supplier', 'process_purchase_return',
  '_product_inv_remove_fifo', '_product_inv_add', '_product_inv_move',
  '_raw_remove_fifo', '_raw_add', '_post_journal_entry', 'post_manual_journal',
  'create_production_order', 'complete_production_order', 'cancel_production_order',
  'create_warehouse_transfer', 'approve_warehouse_transfer', 'reject_warehouse_transfer',
  'get_income_statement', 'get_balance_sheet', 'get_trial_balance', 'get_general_ledger',
  'get_journals', 'get_aging_summary', 'get_audit_trail', 'get_treasury_balances',
  'get_cash_flow', 'get_open_invoices', 'get_party_statement', 'resolve_account_key',
  'ensure_chart_of_accounts', 'guard_user_role_changes', 'protect_last_admin',
  'create_order', 'set_order_status', 'set_table_status',
  'send_to_kitchen',
  'login_as_user', 'return_from_login_as', 'record_login_failure', 'record_login_success',
  'create_purchase_request', 'update_purchase_request_status', 'create_rfq', 'update_rfq_status',
  'record_supplier_quotation', 'select_supplier_quotation', 'get_rfq_comparison',
  'create_purchase_order', 'update_purchase_order_status', 'receive_purchase_order',
  'get_purchase_backorders', 'get_purchase_receipts', 'get_supplier_evaluation',
  'get_supplier_price_impact', 'get_raw_material_cost_overview', 'get_raw_material_cost_valuation_overview', 'get_raw_material_cost_history',
  'can_execute_cloud_print_kind', 'sync_kitchen_sent_quantity_after_void',
  '_normalize_thermal_print_payload', 'normalize_cloud_thermal_print_job',
];

function loadContract() {
  const file = join(ROOT, 'supabase', 'api-contract.json');
  try {
    const c = JSON.parse(readFileSync(file, 'utf8'));
    return {
      tables: c.tables,
      rpcs: c.rpcs.map((r) => r.name),
    };
  } catch {
    console.error('ERROR: supabase/api-contract.json missing. Run `node scripts/db/gen-contract.js` first.');
    process.exit(1);
  }
}

function loadEnv(filePath) {
  const env = {};
  let raw;
  try {
    raw = readFileSync(filePath, 'utf8');
  } catch {
    return env;
  }
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (key) env[key] = value;
  }
  return env;
}

function buildSsl(connectionString) {
  const sslMode = (connectionString.match(/sslmode=([^&\s]+)/) || [])[1];
  if (sslMode && sslMode !== 'disable') return { rejectUnauthorized: false };
  return false;
}

async function main() {
  const env = loadEnv(join(ROOT, '.env'));
  const dbUrl =
    process.env.SUPABASE_DB_URL || process.env.DATABASE_URL || process.env.POSTGRES_URL ||
    env.SUPABASE_DB_URL || env.DATABASE_URL || env.POSTGRES_URL;
  if (!dbUrl) {
    console.error('ERROR: no database URL found. Add SUPABASE_DB_URL (or DATABASE_URL) to .env.');
    process.exit(1);
  }

  const client = new pg.Client({ connectionString: dbUrl, ssl: buildSsl(dbUrl) });
  await client.connect();

  const tableRows = await client.query(
    `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`,
  );
  const existingTables = new Set(tableRows.rows.map((r) => r.table_name));

  const fnRows = await client.query(
    `SELECT proname FROM pg_proc WHERE pronamespace = 'public'::regnamespace GROUP BY proname`,
  );
  const existingFns = new Set(fnRows.rows.map((r) => r.proname));

  const missingTables = EXPECTED_TABLES.filter((t) => !existingTables.has(t));
  const missingFns = EXPECTED_FUNCTIONS.filter((f) => !existingFns.has(f));

  // Safety invariant: cloud queue execution is transport, not the originating
  // business action. A receipt-capable terminal must be able to drain already
  // authorized kitchen/bar jobs; otherwise durable jobs silently pile up.
  let kitchenVoidInvariantOk = false;
  let kitchenVoidInvariantDetail = '';
  if (existingFns.has('sync_kitchen_sent_quantity_after_void')) {
    const { rows } = await client.query(
      `SELECT lower(pg_get_functiondef('public.sync_kitchen_sent_quantity_after_void()'::regprocedure)) AS definition`,
    );
    const def = rows[0]?.definition || '';
    const alignsToCurrentQuantity =
      (
        def.includes('set sent_quantity = greatest(coalesce(v_current_quantity, 0), 0)')
        || (
          def.includes('v_target_quantity := greatest(coalesce(v_current_quantity, 0), 0)')
          && def.includes('set sent_quantity = v_target_quantity')
        )
      )
      && def.includes('from public.order_items oi')
      && def.includes('where oi.id = new.order_item_id');
    const legacyDoubleSubtract =
      def.includes('sent_quantity - new.quantity')
      || def.includes('sent_quantity = greatest(sent_quantity - new.quantity');
    const skipsNoopUpdate =
      def.includes('sent_quantity is distinct from v_target_quantity');
    kitchenVoidInvariantOk =
      alignsToCurrentQuantity && skipsNoopUpdate && !legacyDoubleSubtract;
    if (!kitchenVoidInvariantOk) {
      kitchenVoidInvariantDetail =
        'sync_kitchen_sent_quantity_after_void must align sent_quantity to the current order-item quantity, skip no-op updates, and never subtract NEW.quantity a second time.';
    }
  }

  let thermalPrintPayloadInvariantOk = false;
  let thermalPrintPayloadInvariantDetail = '';
  if (
    existingFns.has('_normalize_thermal_print_payload')
    && existingFns.has('normalize_cloud_thermal_print_job')
  ) {
    const [{ rows: normalizerRows }, { rows: triggerRows }] = await Promise.all([
      client.query(
        `SELECT lower(pg_get_functiondef('public._normalize_thermal_print_payload(jsonb)'::regprocedure)) AS definition`,
      ),
      client.query(
        `SELECT lower(pg_get_triggerdef(oid)) AS definition
         FROM pg_trigger
         WHERE tgrelid='public.cloud_print_jobs'::regclass
           AND tgname='trg_normalize_cloud_thermal_print_job'
           AND NOT tgisinternal`,
      ),
    ]);
    const normalizer = normalizerRows[0]?.definition || '';
    const triggerDef = triggerRows[0]?.definition || '';
    const stripsHtml = normalizer.includes("p_payload - 'html'");
    const createsText = normalizer.includes("jsonb_build_object('text', v_text)");
    const guardsQueue =
      triggerDef.includes('before insert or update of payload, kind')
      && triggerDef.includes('normalize_cloud_thermal_print_job()');
    thermalPrintPayloadInvariantOk = stripsHtml && createsText && guardsQueue;
    if (!thermalPrintPayloadInvariantOk) {
      thermalPrintPayloadInvariantDetail =
        'receipt/report cloud jobs must be normalized to text at the cloud_print_jobs queue boundary; raw HTML/CSS must never reach the thermal text transport.';
    }
  }

  let cloudPrintTransportInvariantOk = false;
  let cloudPrintTransportInvariantDetail = '';
  if (existingFns.has('can_execute_cloud_print_kind')) {
    const { rows } = await client.query(
      `SELECT lower(pg_get_functiondef('public.can_execute_cloud_print_kind(text)'::regprocedure)) AS definition`,
    );
    const def = rows[0]?.definition || '';
    const hasKnownKinds = def.includes("p_kind in ('kitchen','receipt','report')");
    const hasReceiptCapability = def.includes("can_permission('pos.receipt.print')");
    const hasKitchenCapability = def.includes("can_permission('pos.print_kitchen')");
    const hasSettingsCapability = def.includes("can_permission('settings.manage')");
    const reintroducesPerKindCoupling =
      def.includes("p_kind = 'kitchen' and public.can_permission('pos.print_kitchen')")
      || def.includes("p_kind in ('receipt','report') and public.can_permission('pos.receipt.print')");
    cloudPrintTransportInvariantOk =
      hasKnownKinds
      && hasReceiptCapability
      && hasKitchenCapability
      && hasSettingsCapability
      && !reintroducesPerKindCoupling;
    if (!cloudPrintTransportInvariantOk) {
      cloudPrintTransportInvariantDetail =
        'can_execute_cloud_print_kind must allow any operational print-capable branch terminal to transport kitchen/receipt/report jobs without coupling the current user permission to the queued job kind.';
    }
  }

  // Frontend contract: every RPC/table the frontend calls must exist.
  const contract = loadContract();
  const contractMissingTables = contract.tables.filter((t) => !existingTables.has(t));
  const contractMissingRpcs = contract.rpcs.filter((f) => !existingFns.has(f));

  console.log(`Tables:  ${EXPECTED_TABLES.length} expected, ${EXPECTED_TABLES.length - missingTables.length} present`);
  console.log(`Functions: ${EXPECTED_FUNCTIONS.length} expected, ${EXPECTED_FUNCTIONS.length - missingFns.length} present`);
  console.log(`Contract RPCs: ${contract.rpcs.length} expected, ${contract.rpcs.length - contractMissingRpcs.length} present`);
  console.log(`Contract tables: ${contract.tables.length} expected, ${contract.tables.length - contractMissingTables.length} present`);
  console.log(`Kitchen void idempotency invariant: ${kitchenVoidInvariantOk ? 'OK' : 'FAILED'}`);
  console.log(`Thermal print payload invariant: ${thermalPrintPayloadInvariantOk ? 'OK' : 'FAILED'}`);
  console.log(`Cloud print transport invariant: ${cloudPrintTransportInvariantOk ? 'OK' : 'FAILED'}`);

  if (missingTables.length) {
    console.error('\nMissing tables:');
    missingTables.forEach((t) => console.error(`  - ${t}`));
  }
  if (missingFns.length) {
    console.error('\nMissing functions:');
    missingFns.forEach((f) => console.error(`  - ${f}`));
  }
  if (contractMissingTables.length) {
    console.error('\nFrontend contract missing tables (database is behind the frontend):');
    contractMissingTables.forEach((t) => console.error(`  - ${t}`));
  }
  if (contractMissingRpcs.length) {
    console.error('\nFrontend contract missing RPCs (database is behind the frontend):');
    contractMissingRpcs.forEach((f) => console.error(`  - ${f}`));
  }

  if (!kitchenVoidInvariantOk) {
    console.error('\nKitchen void idempotency invariant failed:');
    console.error(`  - ${kitchenVoidInvariantDetail || 'sync_kitchen_sent_quantity_after_void is missing or unsafe'}`);
  }

  if (!thermalPrintPayloadInvariantOk) {
    console.error('\nThermal print payload invariant failed:');
    console.error(`  - ${thermalPrintPayloadInvariantDetail || 'receipt/report queue normalization is missing or unsafe'}`);
  }

  if (!cloudPrintTransportInvariantOk) {
    console.error('\nCloud print transport invariant failed:');
    console.error(`  - ${cloudPrintTransportInvariantDetail || 'can_execute_cloud_print_kind is missing or unsafe'}`);
  }

  const version = await client.query('SELECT version()');
  console.log(`\nServer: ${version.rows[0].version.split(',')[0]}`);
  await client.end();

  if (
    missingTables.length
    || missingFns.length
    || contractMissingTables.length
    || contractMissingRpcs.length
    || !kitchenVoidInvariantOk
    || !thermalPrintPayloadInvariantOk
    || !cloudPrintTransportInvariantOk
  ) {
    process.exit(1);
  }
  console.log('\nSchema verification passed.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
